name: CI

on:
  push:
    branches: [ "master", "ci/setup-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck xclip pass make uuid-runtime --yes
    - name: Run check
      run: make check
